### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-comments#221]
## Acceptance Criteria

- [x] Works on SS4
- [x] Beta tag released

## Tasks

- [x] #211 Convert to vendor module
- [x] #219 Fix UI display issues in admin
- [x] Ensure gridfield bulk editing tools implementation is working correctly

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-comments/pull/222
- [x] https://github.com/colymba/GridFieldBulkEditingTools/pull/156
- [x] https://github.com/silverstripe/silverstripe-comments/pull/224

**Comment by robbieaverill** [comment]
@be2n there's some useful convo around this here: https://github.com/silverstripe/comment-notifications/issues/25

We were discussing whether we could remove the gridfield bulk editing tools module as a dependency, or whether the feature it provides (bulk actions for comments) is worth keeping.

**Comment by robbieaverill** [comment]
@NightJar do you know/remember whether this module is ready now to be tagged as beta? Last remaining task to close this issue

**Comment by robbieaverill** [comment]
Seems pretty good for beta

**Comment by robbieaverill** [comment]
Beta tag released: https://github.com/silverstripe/silverstripe-comments/releases/tag/3.0.0-beta1
